### ISSUE TITLE
 SplashFragment_.builder().build()

### ISSUE THREAD

**Issue by ChinaRobin** [free46000/HybridFoundation#1]
1. SplashFragment_.builder().build()
can not resolve symbol "SplashFragment_."( SplashFragment_. 这个在代码中标红，并且找不到)
2 Manifest.xml里面的  <activity android:name=".MainActivity_">
MainActivity_" 也报红找不到，需要新建
这是怎么回事？谢谢~

**Comment by free46000** [comment]
你那边是不是依赖没有构建成功，没有编译通过，这些带下划线的类都是AndroidAnnotation自动生成的
@ChinaRobin
