### ISSUE TITLE
关于splash解决白屏问题的一点意见

### ISSUE THREAD

**Issue by dicallc** [free46000/HybridFoundation#2]
其实很早就下了代码了，最近也有时间看了下
首先呢，我现在做的项目也有很多动态更新的，跳转到Activity界面，这中间大概有2秒的白屏时间

我自己实际测试，解压代码并不需要多少时间，反而是webview的渲染，这里才是大头，所以我觉得只要监听webview加载完就隐藏Fragment即可，不需要那么复杂的设置延时，什么的吧。
监听：
```

   mWebview.setWebChromeClient(new WebChromeClient(){
      @Override public void onProgressChanged(WebView mWebView, int num) {
        super.onProgressChanged(mWebView, num);
        if (100==num){
          hideTranstion();
        }
      }
    });

```
PS:我很久没用RXjava了，所以不知道理解你代码中的Splash处理有不有错

当然楼主的使用fragment显示页面这个ideal很赞.

当然其实你可以看看Cordova中的处理，很健全，因为我现在项目用的是ionic，所以基本使用他来加载的

最后，谢谢你的分享，对于H5的差异化区别，然后下载新编写即可，我也准备研究，不知道能不能分享一下

**Comment by free46000** [comment]
设置延时是为了更灵活，如有的需求是最少展示闪屏两秒。
目前隐藏闪屏需要同时满足两个条件：1.展示时长满足设置的闪屏时长；2.webview加载完成

还没有看过Cordova源码，但是你说ionic这个是前端框架，配合angular使用，我这边用的vue

差异化是本地储存个标识可以是版本号或者更新时间，前端代码通过webpack会build出来每个版本的代码，这样在客户端需要的时候携带标识，服务端会对比和最新版本的文件差异，压缩后返回客户端即可
